name: Herzliche Begrüßung

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Sende Begrüßungsnachricht für Issues
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Vielen Dank für Ihr Issue! Wir werden uns so schnell wie möglich darum kümmern."
    - name: Sende Begrüßungsnachricht für Pull Requests
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: "Vielen Dank für Ihren Pull Request! Unser Team wird ihn überprüfen."
